[command]
default=verpy-run python $ROSE_SUITE_DIR/app/run_verpy_plotting/bin/verpy_plotting_precip_monitoring.py --vdate $CYLC_TASK_CYCLE_POINT --fcrs $LEAD_SEQ --met-source $MET_SOURCE --outdir $OUTDIR --truth-type $TRUTH --accumulation $ACCUM_PERIOD

[env]
# Environment variables are already set in flow.cylc