[template variables]
START_CYCLE_POINT='20250126T0000Z'
FINAL_CYCLE_POINT='20250129T0000Z'
SCITOOLS='scitools/default-next'
OEMPLOT_CONDA_ENV='/home/users/uktstbed/conda_envs/oemplotlib/py38_iris32_20250124'
CYCLING_ON='VT'
TRIAL1='mi-bg180' 
TRIAL2='mi-bg181'
DATA_DIR='/data/users/sebastian.cole/GM_precip'
PROCESSED_DIR='/data/users/sebastian.cole/processed_accums'
OUTPUT_BASE='/data/scratch/sebastian.cole/GM_precip_testing'
GPM_DATA_DIR='/data/users/gpm_imerg'
GPM_OBS_TYPE='GPM_NRTlate'
###AREA_MASKS='/data/users/cfver/MET_Repos/AreaMasks/poly_euro.nc'
AREA_MASKS=['/data/users/sebastian.cole/GM_precip/poly_euro.nc', '/data/users/sebastian.cole/GM_precip/poly_globe.nc']
PREP='DT'
MET_OUTPUT_DIR='/data/scratch/sebastian.cole/global_precip_stand_alone'

 